name: tests

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      # Install .NET SDK
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            9.0.x

      # Invoke tests
      - name: Invoke tests on net8.0
        run: dotnet run --project ./Tests/BlazingStory.Test -f net8.0
      - name: Invoke tests on net9.0
        run: dotnet run --project ./Tests/BlazingStory.Test -f net9.0
