name: tests

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v3

      # Install .NET SDK
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
           dotnet-version: |
             7.0.x
             8.0.100-preview.6.23330.14

      # Invoke tests
      - name: Invoke tests
        run: dotnet test -p:TypeScriptCompileBlocked=true
